name: Creando release
on:
  push:
    branches:
      - develop

jobs:
  pruebas:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Integracion') }}
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.9'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas ${{ github.ref }}
      id: correr-pruebas
      run: python -m unittest -v tests/TestLogicaCaja.py
    - name: Cálculo de cubrimiento
      id: cubrimiento
      run: |
          coverage run -m unittest tests/TestLogicaCaja.py
          coverage report -m
    - name: Crear rama release
      uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        branch: 'release'
    - name: Correr pruebas ${{ github.ref }}
      id: correr-pruebas
      run: python -m unittest -v tests/TestLogicaCaja.py
    - name: Cálculo de cubrimiento
      id: cubrimiento
      run: |
        coverage run -m unittest tests/TestLogicaCaja.py
        coverage report -m
    - name: Merge ${{ github.ref }} -> main
      if: success()
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        source-branch: release
        target-branch: main