name: Comprobando feature realizada
on:
  push:
    branches:
      - feature**

jobs:
  pruebas:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'FIXED') }}
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.9'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest -v tests/TestLogicaCaja.py
    - name: Cálculo de cubrimiento
      id: cubrimiento
      run: |
          coverage run -m unittest tests/TestLogicaCaja.py
          coverage report -m
    - name: Merge ${{ github.ref }} -> develop
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        source-branch: ${{ github.ref }}
        target-branch: develop
        commit-message: "Integracion de funcionalidad desde ${{ github.ref }}"

